name: MCPanel
options:
  bundleIdPrefix: md.thomas
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: MCPanel
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: "1.2.0"

targets:
  MCPanel:
    type: application
    platform: macOS
    sources:
      - path: mcpanel
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: md.thomas.mcpanel
        INFOPLIST_FILE: mcpanel/Info.plist
        CODE_SIGN_ENTITLEMENTS: mcpanel/MCPanel.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: SwiftTerm
    entitlements:
      path: mcpanel/MCPanel.entitlements

schemes:
  MCPanel:
    build:
      targets:
        MCPanel: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
